### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by danrichman** [GShotwell/vitamin_d_covid#15]
Ideally this document should be run through a spell-checker. A few issues that need correcting:

>Panagiotou eet

Panagiotou `et`

>Iranian hospital found that vitamin D deficiency and ACE disregulation were more commone among those who tested positive for Covid-19

Iranian hospital found that vitamin D deficiency and ACE `dysregulation` were more `common` among those who tested positive for Covid-19

>A Germnan Study

A `German` Study

>smallprospective

`small prospective`

>Isreal et al

`Israel` et al

>Isreali vitamin D tests  Israeli

`Israeli` vitamin D tests

(Ideally should have been fixed in #14)

>Mendelian randomisation analysis

Mendelian `randomization` analysis

>2020 metaanalysis

2020 `meta-analysis`

>Other revies

Other `reviews`

>more than an acausal one

more than an `a causal` one

>preventative and adjuvent therapy

preventative and `adjuvant` therapy

>eliminate Vitamin D deficencies

eliminate Vitamin D `deficiencies`

**Comment by gshotwell** [comment]
Thanks, in the future can you just do a pull request?
